name: uniscan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #! Architecture
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  auto_route: ^5.0.4

  #! Firebase
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  #! Widgets
  font_awesome_flutter: ^10.3.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^5.1.1

  #! Utils
  async: ^2.9.0
  cupertino_icons: ^1.0.2
  figma_squircle: ^0.5.3
  dartz: ^0.10.1
  connectivity: ^3.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  logger: ^2.3.0
  dio: ^4.0.6
  permission_handler: ^11.3.1
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #! Code generators
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2

  flutter_launcher_icons: ^0.9.2
  mockito: ^5.4.4
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "#000000"
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/
  fonts:
    - family: NAMU
      fonts:
        - asset: fonts/NAMU-Pro.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
