name: uniscan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  url_launcher: ^6.2.6
  figma_squircle: ^0.5.3
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^4.0.1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity: ^3.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  mockito: ^5.4.4
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "#000000"
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/
  fonts:
    - family: NAMU
      fonts:
        - asset: fonts/NAMU-Pro.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
